export const buddhism = [
  {
    title: "Lời Phật dạy",
    content: [
      "Đừng tin tưởng vào một điều gì vì phong văn. Đừng tin tưởng điều gì vì vin vào một tập quán lưu truyền.",
      "Đừng tin tưởng điều gì vì cớ được nhiều nói đi nhắc lại. Đừng tin tưởng điều gì dù là bút tích của thánh nhân.",
      "Đừng tin tưởng điều gì dù thói quen từ lâu khiến ta nhận là điều ấy đúng.",
      "Đừng tin tưởng điều gì do ta tưởng tượng ra lại nghĩ rằng một vị tối linh đã khai thị cho ta.",
      "Đừng tin tưởng bất cứ một điều gì chỉ vin vào uy tín của các thầy dạy các người.",
      "Nhưng chỉ tin tưởng cái gì mà chính các người đã từng trải, kinh nghiệm và nhận là đúng, có lợi cho mình và người khác. Chỉ có cái đó mới là đích tối hậu thăng hoa cho con người và cuộc đời. Các người hãy lấy đó làm chỉ chuẩn."
    ]
  },
  {
    title: "10 Điều chớ vội tin",
    content: [
      "1. Chớ vội tin điều gì, chỉ vì điều đó là truyền thuyết.",
      "2. Chớ vội tin điều gì, chỉ vì điều đó thuộc về truyền thống.",
      "3. Chớ vội tin điều gì, chỉ vì điều đó được nhiều người nhắc đến hay tuyên truyền.",
      "4. Chớ vội tin điều gì, chỉ vì điều đó được ghi lại trong sách vở hay kinh điển.",
      "5. Chớ vội tin điều gì, chỉ vì điều đó lý luận siêu hình.",
      "6. Chớ vội tin điều gì, chỉ vì điều đó phù hợp với lập trường của mình.",
      "7. Chớ vội tin điều gì, chỉ vì điều ấy phù hợp với định kiến của mình.",
      "8. Chớ vội tin điều gì, khi điều đó được căn cứ trên những dữ kiện hời hợt.",
      "9. Chớ vội tin điều gì, chỉ vì điều ấy được sức mạnh và quyền uy ủng hộ.",
      "10. Chớ vội tin điều gì, chỉ vì điều ấy được các nhà truyền giáo hay đạo sư của mình tuyên thuyết."
    ]
  },
  {
    title: "Bát chánh đạo",
    content: [
      "Bát Chánh Đạo – Con Đường Giải Thoát\n\nBát Chánh Đạo là con đường thực hành giúp con người thoát khỏi khổ đau, đạt đến trí tuệ và giải thoát. Đây không chỉ là những nguyên tắc đạo đức mà còn là phương pháp sống tỉnh thức, dẫn dắt con người đến sự an lạc và giác ngộ. Tám yếu tố này được chia thành ba nhóm chính:\n\n1. Nhận thức đúng đắn (Trí tuệ – Tuệ học)\n\nChánh kiến: Thấy rõ bản chất của thực tại, hiểu đúng về nhân quả, vô thường, vô ngã.\n\nChánh tư duy: Suy nghĩ thiện lành, không bị chi phối bởi tham, sân, si, hướng đến từ bi và giải thoát.\n\n2. Hành vi đúng đắn (Đạo đức – Giới học)\n\nChánh ngữ: Lời nói chân thật, hòa ái, không nói dối, không gây chia rẽ, không ác khẩu.\n\nChánh nghiệp: Hành động chân chính, không sát sinh, không trộm cắp, không tà dâm.\n\nChánh mạng: Nghề nghiệp lương thiện, nuôi sống bản thân mà không làm tổn hại đến người và chúng sinh.\n\n3. Tu tập tâm thức (Thiền định – Định học)\n\nChánh tinh tấn: Nỗ lực không ngừng trong việc từ bỏ điều xấu, nuôi dưỡng điều thiện.\n\nChánh niệm: Sống tỉnh thức trong từng giây phút, không để tâm bị cuốn vào vọng tưởng.\n\nChánh định: Tâm an trú vững vàng, đạt đến sự tĩnh lặng và trí tuệ sâu sắc.\n\nSự Liên Kết của Bát Chánh Đạo\n\nBát Chánh Đạo không phải tám con đường riêng biệt mà là tám yếu tố hỗ trợ nhau. Khi có Chánh kiến, ta sẽ có Chánh tư duy; khi tư duy đúng, lời nói và hành động sẽ chân chính. Khi sống đúng, tâm sẽ an định, từ đó tinh tấn, tỉnh thức và đạt đến giải thoát.\n\nThực hành Bát Chánh Đạo không phải là chấp vào một khuôn khổ cứng nhắc mà là sự chuyển hóa dần dần, giúp con người thoát khỏi phiền não, đạt được trí tuệ và từ bi. Đây chính là con đường dẫn đến vô ngã, buông bỏ chấp trước, và hòa nhập với chân lý của vũ trụ."
    ]
  }
];

export const imagesPersonal = [
  "/personal-growth/PTBT-05.jpg",
  "/personal-growth/growth-01.jpg",
  "/personal-growth/growth-03.jpg",
  "/personal-growth/growth-02.jpg",
  "/personal-growth/PTBT-06.jpg",
  "/personal-growth/PTBT-09.webp",
  "/personal-growth/growth-04.webp",
  "/personal-growth/growth-05.webp",
  "/personal-growth/growth-06.webp",
  "/personal-growth/growth-07.webp",
  "/personal-growth/growth-08.jpg",
  "/personal-growth/growth-09.webp",
  "/personal-growth/growth-10.webp",
  "/personal-growth/growth-11.webp",
  "/personal-growth/growth-12.jpg",
  "/personal-growth/growth-13.jpg",
  "/personal-growth/growth-14.png",
  "/personal-growth/growth-16.png",
  "/personal-growth/growth-17.png",
  "/personal-growth/growth-18.png",
  "/personal-growth/growth-19.png",
  "/personal-growth/growth-20.png",
  "/personal-growth/growth-21.png",
  "/personal-growth/growth-22.png",
  "/personal-growth/growth-23.png",
  "/personal-growth/growth-25.png",
  "/personal-growth/growth-26.png",
  "/personal-growth/growth-27.png",
  "/personal-growth/growth-28.png",
  "/personal-growth/growth-29.png",
  "/personal-growth/growth-30.png",
  "/personal-growth/growth-31.png",
  "/personal-growth/growth-32.png",
  "/personal-growth/growth-33.png",
  "/personal-growth/growth-34.png",
  "/personal-growth/growth-35.png",
  "/personal-growth/growth-36.png",
  "/personal-growth/growth-37.png",
  "/personal-growth/growth-38.png",
  "/personal-growth/growth-39.png",
  "/personal-growth/growth-40.png",
  "/personal-growth/growth-41.png",
  "/personal-growth/growth-42.png",
  "/personal-growth/growth-43.png",
  "/personal-growth/growth-44.png",
  "/personal-growth/growth-45.png",
  "/personal-growth/growth-46.png",
  "/personal-growth/growth-47.png",
  "/personal-growth/growth-48.png",
  "/personal-growth/growth-49.png",
  "/personal-growth/growth-50.png",
  "/personal-growth/growth-51.png",
  "/personal-growth/growth-52.png",
  "/personal-growth/growth-53.png",
  "/personal-growth/growth-54.png",
  "/personal-growth/growth-55.png",
  "/personal-growth/growth-56.png",
  "/personal-growth/growth-57.png",
  "/personal-growth/growth-58.png",
  "/personal-growth/growth-59.png",
  "/personal-growth/growth-60.png",
  "/personal-growth/growth-61.png",
  "/personal-growth/growth-62.png",
  "/personal-growth/growth-63.png",
  "/personal-growth/growth-64.png",
  "/personal-growth/growth-65.png",
  "/personal-growth/growth-66.png",
  "/personal-growth/growth-67.png",
  "/personal-growth/growth-68.png",
  "/personal-growth/growth-69.png",
  "/personal-growth/growth-70.png",
  "/personal-growth/growth-71.png",
  "/personal-growth/growth-72.png"
];
