export const experience = [
  {
    title: "Sự Bình An",
    content: [
      "Có rất nhiều người chọn cách là ngồi hàng giờ trước máy tính, để giao dịch mua bán loạn xạ, nhưng có rất nhiều người họ chọn phong cách rất nhẹ nhàng, họ thưởng thức ly trà, họ đọc sách, nghiền ngẫm và những lệnh của họ vẫn tạo ra lợi nhuận rất tốt, vậy thì trong trading không phải cứ giao dịch nhiều là tốt mà yếu tố lợi nhuận phải đặt lên hàng đầu, vào lệnh giao dịch phải làm sao tối ưu được, phải chọn được điểm vào lệnh đẹp, tối ưu được khi lợi nhuận nó đến, và cắt lỗ sớm nhất khi mà thua lỗ nó đến, làm sao thua lỗ phải ít và lợi nhuận cứ để cho nó chạy, nhưng đám đông toàn làm ngược lại.\n\nKhi hiểu được quy luật vận hành của thị trường thì chúng ta cần biết cách kiên nhẫn chờ đợi, nhiều người chờ đợi trong một trạng thái rất là bất an, lo lắng, nhỡ ra lỡ con sóng này thì sao, nhỡ giá nó tăng nữa mà nó không về vùng mua thì sao, lúc này chúng ta lại nôn nóng hấp tấp vào mua, rồi vẫn là những khoản thua lỗ, những thứ này để hiểu được cần một quá trình dài đi cùng thị trường, và khi hiểu được thì đầu tư rất là nhẹ nhàng, thoải mái và bình an.\n\nNếu đi với thị trường tài chính thì đừng để những cây nến xanh đỏ nó làm ảnh hưởng tới tâm lý của chúng ta, đừng để thị trường nó dày vò chúng ta, thì để làm được điều này cần phải thực sự hiểu được bản chất, phải làm sao đào sâu vào trong tâm thức, vì chỉ khi đào sâu vào trong tâm thức thì chúng ta mới hiểu được ý nghĩa của việc trading và đầu tư, cái sự quý giá của sự bình an trong trading và đầu tư..."
    ]
  },
  {
    title: "Sự nghiêm túc",
    content: [
      "Để có thể đi đường dài cùng với thị trường thì bắt buộc mỗi cá nhân phải tự xây dựng cho mình một hệ thống giao dịch, việc này tốn rất nhiều thời gian và công sức.\n\nĐa số nhiều người thua là bởi vì họ không có một hệ thống giao dịch, không thực sự có tư duy đúng về nghề, không thật sự nghiêm túc đào sâu đến tận cùng.\n\nSẽ là vô nghĩa nếu thắng được 3 tháng, 6 tháng....nhưng lại thua hết tất cả trong 1 ngày...\n\nThế nên, chỉ có hệ thống giao dịch và ý thức tuân thủ nó tuyệt đối, cũng như quản trị tâm, hiểu chính mình...đó là chìa khoá giúp bạn đi xa và hiểu về nghề này.\n\nHãy cứ thật chậm rãi, làm tốt bài toán quản trị rủi ro trong quá trình xây dựng hệ thống giao dịch. Chắc chắn các bạn sẽ đối diện rất nhiều khó khăn, nhưng thực sự...khó khăn càng lớn, có những cú tát càng đau...thì bài học mới thấm.\n\nNhưng nhớ kỹ: Đừng để nhiều bài học đau đớn đến với bạn...vì sẽ có nhiều người sẽ gục ngã và ko vượt qua được.\n\nHãy làm tốt bài toán quản trị rủi ro, hãy làm sao cho phép mình có cơ hội làm lại, hãy làm sao thua mà ko ảnh hưởng gì đến cuộc sống của bạn. Cách tốt nhất là dùng một số tiền rất nhỏ, giao dịch cực kỳ thận trọng...và bài học sẽ hình thành.."
    ]
  },
  {
    title: "Quy luật nhân quả",
    content: [
      "Quy luật nhân quả trong đầu tư cũng như trong cuộc sống...\n\n Muốn có được cái QUẢ là đầu tư THẮNG kiếm được nhiều tiền, thì cái nhân gieo bây giờ là sự hiểu biết, kiến thức, đi cùng thị trường, tận tâm, nỗ lực, đào sâu, phải giỏi thì quả ngọt sẽ đến.\n\n Nếu gieo QUẢ là sự ỷ lại vào người khác, không có sự nỗ lực thì chắc chắn sẽ đến giai đoạn thị trường khó xử lý, và nếu không có kĩ năng thực sự thì sẽ không biết xử lý như thế nào...\n\nNó không hề đơn giản đâu, nó là một quá trình phát triển bản thân, đào sâu tâm thức...hoàn thiện chính mình...\n\nGừng càng già càng cay, khi già đi thì sức khoẻ giảm, khó có thể làm những công việc chân tay mãi được, chắc chắn phải dùng trí tuệ để kiếm tiền và xây dựng danh mục tài sản lớn."
    ]
  },
  {
    title: "Lộ Trình Phát Triển Của Một Trader",
    content: [
      "HÀNH TRÌNH CỦA MỘT TRADER PHẢI TRẢI QUA:\n\nGiai đoạn 1: Ngây thơ vô số tội, không có một kĩ năng hay kiến thức gì về trading, nghe ai đó nói là trading kiếm tiền dễ quá, thấy người ta show lãi và tìm đến trading, vào thị trường với suy nghĩ rất ngây thơ là vào để kiếm tiền, nhưng họ không ý thức được kiến thức và năng lực của họ chưa có, chưa có thái độ open để học tập, nên giai đoạn này đa số sẽ bỏ cuộc vì thua lỗ, không kiếm được tiền...\n\nGiai đoạn 2: Ý thức được việc là à, để có thể kiếm được tiền trong thị trường này thì cần phải học tập, trang bị kiến thức, tuy nhiên là chưa biết học tập như thế nào, lúc này bắt đầu họ tìm kiếm kiến thức trên mạng internet hoặc mua sách về nghiên cứu, và lúc này họ nghĩ đơn giản là chỉ cần học tập, chỉ cần có một phương pháp hay công cụ chỉ báo nào đó là có thể kiếm được tiền, giống như kiểu đi tìm kiếm chén thánh vậy, và tầm 60% sẽ bị rụng trong giai đoạn này.\n\nGiai đoạn 3: Lúc này họ hiểu ra được là để có thể thành công trong trading thì cần phải có một hệ thống giao dịch cho riêng mình, lúc này họ bắt đầu open để học tập, khi này chỉ tập trung vào việc hoàn thiện hệ thống, và quản trị cảm xúc rất tốt, lúc này không còn đi chống đối lại thị trường, bắt đầu bỏ qua câu chuyện làm giàu nhanh từ trading, hiểu được bài toán quản trị vốn và quản trị rủi ro là như thế nào, và bắt đầu quan sát những người khác và mỉm cười sao ngày trước mình vô minh vậy.\n\nGiai đoạn 4: Hoàn thiện năng lực một cách có ý thức, lúc này họ đã ở một level khá cao rồi , giao dịch theo phương pháp gì sẽ trung thành với phương pháp giao dịch đó, lúc này sẽ tập trung tối ưu hệ thống giao dịch của chính mình, hiểu được câu chuyện thắng thua trong trading là câu chuyện hết sức bình thường, nhưng kiểm soát được số lệnh thua rất là ít, tỉ lệ số lệnh thắng nhiều cũng như gồng lời rất là tốt, cũng như bắt đầu duy trì lợi nhuận một cách ổn định, lúc này tự giao dịch, không tranh luận với bất kì ai, không nói lên hay chia sẻ nhận định ra bên ngoài vì đơn giản họ ý thức được rằng là mình chả biết gì về thị trường nhiều, họ chỉ biết là với đi theo với dự phóng như vậy nếu đúng thì họ kiếm được lợi nhuận bao nhiêu,còn nếu sai thì họ chấp nhận trả giá cho một stoploss là bao nhiêu, và mọi thứ diễn ra rất là nhẹ nhàng, họ xem nhẹ việc được và mất, dù thị trường có đi như thế nào đi nữa họ vẫn rất thoải mái.\n\nGiai đoạn 5: Level cao nhất, lúc này năng lực vô thức, thấy nó là một công việc ngày qua ngày một cách vô cảm, không còn cảm xúc với trading nữa, vào lệnh khi có setup đẹp bằng không đứng ngoài ung dung tự tại..."
    ]
  },
  {
    title: "Sự kì vọng cao quá",
    content: [
      "Thông thường người ta thua lỗ bởi vì sự kỳ vọng vượt quá năng lực của chính họ...\n\nCó những thứ chỉ cần bớt tham lại, nhẹ nhàng quan sát thì bạn đều có thể nhìn ra được.\n\nBạn không phải đang chiến đấu với market, mà bạn chỉ đang chiến đấu với lòng tham của chính mình.\n\nCó những thứ chỉ cần bớt tham lại, mọi chuyện sẽ rất dễ dàng... nhưng khi bạn đẩy lòng tham của mình lớn lên, mong muốn nhiều hơn... thì mọi khó khăn sẽ đến từ đó.\n\nChúng ta KHÔNG THỂ kiểm soát được hướng đi của thị trường, nhưng chúng ta có thể kiểm soát được rủi ro mà chúng ta có thể đối mặt khi mọi thứ đi ngược lại với dự phóng.\n\nNếu bạn tính toán được và biết cách chấp nhận... thì thị trường đi lên, đi xuống hay đi ngang đều nằm trong kế hoạch của bạn cả rồi.\n\nHiểu được những điều này, bạn nương theo thị trường một cách nhẹ nhàng... thật sự những điều này chỉ khi bớt tham lại, bạn sẽ nhìn ra được...\n\nĐiều quan trọng trong đầu tư... đích đến thật sự của bạn muốn gì...\n\nMục tiêu của mình chỉ là đi cùng thị trường và bình an, vậy là đủ 🙂"
    ]
  },
  {
    title: "Sự tập trung",
    content: [
      "Hãy tập trung một thứ cho thật giỏi...mà ra tiền...thay vì cái gì cũng biết mà đang mất tiền!\n\nLý Tiểu Long từng có một câu nói nổi tiếng rằng: Tôi không sợ người luyện 10.000 cú đá, tôi chỉ sợ người luyện 1 cú đá 10.000 lần.\n\nTrong phân tích kĩ thuật cũng vậy, việc bạn sử dụng công cụ chỉ báo nào không quan trọng, bạn biết sử dụng bao nhiêu bộ công cụ chỉ báo càng không có ý nghĩa gì nếu như bạn không thực sự hiểu sâu về bản chất của công cụ chỉ báo đó.\n\nĐôi khi việc biết nhiều phương pháp quá thậm chí còn làm hại chính bạn vì nhiều phương pháp quá thì sinh ra rối loạn đao pháp rồi dẫn đến bị tẩu hỏa nhập ma.\n\nTrong các bộ phim kiếm hiệp thì các đại cao thủ võ lâm thường chỉ có cho mình một món võ công thượng thừa là đã đủ để tung hoành giang hồ được rồi\n\n Rồi chung quy lại là phương pháp của bạn có đang tạo ra lợi nhuận ổn định hay không, với mình thì đích đến vẫn là tìm ra thứ phù hợp với bản thân mình và tiếp tục phát huy nó vậy là đủ."
    ]
  },
  {
    title: "Sự định hướng đúng",
    content: [
      'Cài nút áo đầu tiên đã sai rồi, nhưng đến nút cuối cùng mới phát hiện, vì vậy không thể không cởi hết các nút ra.\n\nCó 1 số việc, ngay từ đầu đã sai rồi, nhưng đến lúc không thể cứu vãn mới chịu thừa nhận.\n\nĐời người, tiếc nuối lớn nhất chính là dễ dàng từ bỏ thứ không nên từ bỏ, nhưng lại cố chấp kiên trì cái không nên kiên trì...\n\nTrong trading cũng vậy, sai lầm lớn nhất là không biết lúc nào nên kiên trì và lúc nào nên từ bỏ.\n\nTừ bỏ quá sớm:\n\nBạn có một phương pháp tốt, nhưng chỉ vì vài lần thua lỗ, bạn bỏ cuộc và đi tìm một phương pháp khác.\n\nBạn cắt lệnh quá sớm vì sợ mất lợi nhuận, nhưng sau đó giá lại đi đúng hướng và bạn bỏ lỡ lợi nhuận lớn.\n\nCố chấp với thứ không nên kiên trì:\n\nGiữ một lệnh thua lỗ quá lâu chỉ vì "hy vọng giá quay lại."\n\nCố gắng "bắt đáy" hoặc "bắt đỉnh" mà không có tín hiệu rõ ràng.\n\nLiên tục nạp tiền để gồng lệnh thay vì chấp nhận sai lầm và học hỏi từ nó.\n\nNắm giữ một đồng coin rác trong khi tài khoản đã chia 3 chia 5, chỉ vì "hi vọng nó sẽ go to the moon".'
    ]
  }
];